version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8071:8081"
    networks:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/docker_atm
    depends_on:
      - some-postgres

  some-postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ciara
      POSTGRES_PASSWORD: changeMe!
      POSTGRES_DATABASE: docker_atm
      PGDATA: /data/postgres
    volumes:
      - ./db-data:/data/postgres
    ports:
      - "5433:5432" #maps the host's port 5433 to the container's port 5432
    networks:
      - postgres
    restart: always

  pgadmin: #access this on localhost:5050
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: